In [76]:
import sys
import pandas as pd
from google.colab import drive

In [93]:
print(sys.version)
print(sys.version_info)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
sys.version_info(major=3, minor=12, micro=13, releaselevel='final', serial=0)

In [77]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [78]:
df_raw = pd.read_csv("/content/drive/MyDrive/CariSurge/EmergencyTriageDataset_Reduced_Dirty.csv")

In [79]:
print(df_raw.shape)
print(df_raw.columns)

(2205, 11)
Index(['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp',
       'RR', 'Fio2'],
      dtype='object')

In [80]:
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [81]:
print(df_raw["Gender"].unique())

['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

In [82]:
gender_map = {
    '0' : 0,
    '1' : 1,
    'male' : 1,
    'female' : 1
}

print(gender_map)

{'0': 0, '1': 1, 'male': 1, 'female': 1}

In [83]:
df_raw["Clean_Gender"] = df_raw["Gender"].astype(str).str.lower().str.strip().map(gender_map)
df_raw["Clean_Gender"]

0       0
1       1
2       1
3       0
4       1
       ..
2200    1
2201    1
2202    1
2203    1
2204    1
Name: Clean_Gender, Length: 2205, dtype: int64

In [84]:
df_raw["Gender"] = df_raw["Clean_Gender"]
df_raw

,ID,Age,Gender,GCS,SBP,DBP,MAP,pulse,Temp,RR,Fio2,Clean_Gender
0,1,34,0,15.0,93,67.0,75.67,128.0,36.8,14.0,21.0,0
1,2,20,1,15.0,130,90.0,103.33,80.0,37.0,16.0,21.0,1
2,3,77,1,14.0,163,105.0,124.33,92.0,36.8,18.0,21.0,1
3,4,23,0,8.0,100,60.0,73.33,100.0,37.0,12.0,100.0,0
4,5,86,1,15.0,150,90.0,110.00,85.0,37.0,19.0,21.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2200,2380,65,1,14.0,170,50.0,90.00,65.0,37.0,22.0,21.0,1
2201,2381,84,1,15.0,180,120.0,140.00,85.0,36.1,18.0,21.0,1
2202,2382,78,1,15.0,132,78.0,96.00,100.0,37.9,16.0,21.0,1
2203,2383,65,1,15.0,140,80.0,100.00,85.0,36.4,16.0,21.0,1
2204,2384,78,1,15.0,145,90.0,108.33,75.0,37.6,20.0,21.0,1

In [90]:
df_raw = df_raw.drop(columns=["Clean_Gender"])

In [92]:
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20       1  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77       1  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86       1  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42       1  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75       1  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25       1  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82       1  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0